In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('./datasets/train_u6lujuX_CVtuZ9i.csv')

In [3]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [6]:
df['Married'] = df['Married'].fillna(df['Gender'].mode()[0])

In [7]:
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].mean())

In [8]:
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])

In [9]:
df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])

In [10]:
df.select_dtypes(include=object).columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [11]:
df['Self_Employed'] = df['Self_Employed'].map({
    'Yes': 1,
    'No': 0
})

In [12]:
df['Self_Employed'].dtype

dtype('int64')

In [13]:
df['Credit_History'].dtype

dtype('float64')

In [14]:
df['LoanAmount'].dtype

dtype('float64')

In [15]:
df['ApplicantIncome'].dtype

dtype('int64')

In [16]:
X = df[['ApplicantIncome', 'LoanAmount', 'Credit_History', 'Self_Employed']]
y = df['Loan_Status']

In [17]:
import seaborn as sns

sns.boxplot

<function seaborn.categorical.boxplot(data=None, *, x=None, y=None, hue=None, order=None, hue_order=None, orient=None, color=None, palette=None, saturation=0.75, fill=True, dodge='auto', width=0.8, gap=0, whis=1.5, linecolor='auto', linewidth=None, fliersize=None, hue_norm=None, native_scale=False, log_scale=None, formatter=None, legend='auto', ax=None, **kwargs)>

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42 )

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
from sklearn.svm import SVC

svc_linear = SVC(kernel='linear', C=1)
svc_linear.fit(X_train, y_train)
y_pred_linear = svc_linear.predict(X_test)

In [21]:
from sklearn.metrics import classification_report

print('Classification Report for Linear Kernel: \n', classification_report(y_test, y_pred_linear))

Classification Report for Linear Kernel: 
               precision    recall  f1-score   support

           N       0.95      0.42      0.58        43
           Y       0.76      0.99      0.86        80

    accuracy                           0.79       123
   macro avg       0.85      0.70      0.72       123
weighted avg       0.83      0.79      0.76       123



In [22]:
from sklearn.svm import SVC

svc_polynomial = SVC(kernel='poly', C=1, degree=3)
svc_polynomial.fit(X_train, y_train)
y_pred_poly = svc_polynomial.predict(X_test)

In [23]:
print('Classification Report for Polynomial Kernel (Degree = 3): \n', classification_report(y_test, y_pred_poly))

Classification Report for Polynomial Kernel (Degree = 3): 
               precision    recall  f1-score   support

           N       0.95      0.42      0.58        43
           Y       0.76      0.99      0.86        80

    accuracy                           0.79       123
   macro avg       0.85      0.70      0.72       123
weighted avg       0.83      0.79      0.76       123



In [24]:
svc_rbf = SVC(kernel='rbf', C=2, gamma='scale')
svc_rbf.fit(X_train, y_train)
y_pred_rbf = svc_rbf.predict(X_test)

In [25]:
print('Classification Report for RBF kernel: \n', classification_report(y_test, y_pred_rbf))

Classification Report for RBF kernel: 
               precision    recall  f1-score   support

           N       1.00      0.42      0.59        43
           Y       0.76      1.00      0.86        80

    accuracy                           0.80       123
   macro avg       0.88      0.71      0.73       123
weighted avg       0.85      0.80      0.77       123



In [26]:
from sklearn.metrics import confusion_matrix

print('----------------------------------------------')
print('Confusion Matrix of Linear Kernel: \n', confusion_matrix(y_test, y_pred_linear))
print('----------------------------------------------')
print('Classification Report of Polynomial Kernel: \n', confusion_matrix(y_test, y_pred_poly))
print('----------------------------------------------')
print('Classification Report of RBF Kernel: \n', confusion_matrix(y_test, y_pred_rbf))
print('----------------------------------------------')

----------------------------------------------
Confusion Matrix of Linear Kernel: 
 [[18 25]
 [ 1 79]]
----------------------------------------------
Classification Report of Polynomial Kernel: 
 [[18 25]
 [ 1 79]]
----------------------------------------------
Classification Report of RBF Kernel: 
 [[18 25]
 [ 0 80]]
----------------------------------------------
